<%
	SavedFile = "importlogs/save.txt"
	findit = Server.MapPath(Savedfile)
	Set fso = server.CreateObject("Scripting.FileSystemObject")
	Err.number=0
	Set f = fso.OpenTextFile(findit, 1)
	Flines = f.ReadAll
	f.close
	ALines=split(Flines,vbcrlf)
	
	Function CheckField(FDName)
	
		CorrectName=""
		TempStr=FDName & "*****"
		
		For dd=lbound(ALines) to ubound(ALines)

		if instr(ALines(dd),TempStr)>0 then
			
		 Select Case dd+1
		 Case 1: CorrectName="SKU"
		 Case 2: CorrectName="Name"
		 Case 3: CorrectName="Description"
		 Case 4: CorrectName="Short Description"
		 Case 5: CorrectName="Product Type"
		 Case 6: CorrectName="Online Price"
		 Case 7: CorrectName="List Price"
		 Case 8: CorrectName="Wholesale Price"
		 Case 9: CorrectName="Weight"
		 Case 10: CorrectName="Stock"
		 Case 11: CorrectName="Category Name"
		 Case 12: CorrectName="Category Small Image"
		 Case 13: CorrectName="Category Large Image"
		 Case 14: CorrectName="Parent Category"
		 Case 15: CorrectName="Additional Category 1"
		 Case 16: CorrectName="Parent Category 1"
		 Case 17: CorrectName="Additional Category 2"
		 Case 18: CorrectName="Parent Category 2"
		 Case 19: CorrectName="Brand Name"
		 Case 20: CorrectName="Brand Logo"
		 Case 21: CorrectName="Thumbnail Image"
		 Case 22: CorrectName="General Image"
		 Case 23: CorrectName="Detail view Image"
		 Case 24: CorrectName="Active"
		 Case 25: CorrectName="Show savings"
		 Case 26: CorrectName="Special"
		 Case 27: CorrectName="Non-taxable"
		 Case 28: CorrectName="No shipping charge"
		 Case 29: CorrectName="Not for sale"
		 Case 30: CorrectName="Not for sale copy"
		 Case 31: CorrectName="Disregard stock"
		 Case 32: CorrectName="Display No Shipping Text"
		 Case 33: CorrectName="Custom Search Field (1)"
		 Case 34: CorrectName="Custom Search Field (2)"
		 Case 35: CorrectName="Custom Search Field (3)"
		 Case 36: CorrectName="Downloadable File Location"
		 Case 37: CorrectName="Make Download URL expire"
		 Case 38: CorrectName="URL Expiration in Days"
		 Case 39: CorrectName="Use License Generator"
		 Case 40: CorrectName="Local Generator"
		 Case 41: CorrectName="Remote Generator"
		 Case 42: CorrectName="License Field Label (1)"
		 Case 43: CorrectName="License Field Label (2)"
		 Case 44: CorrectName="License Field Label (3)"
		 Case 45: CorrectName="License Field Label (4)"
		 Case 46: CorrectName="License Field Label (5)"
		 Case 47: CorrectName="Additional copy"
		 Case 48: CorrectName="Short Category Description"
		 Case 49: CorrectName="Long Category Description"
		 Case 50: CorrectName="Minimum Quantity customers can buy"
		 Case 51: CorrectName="Reward Points"
		 Case 52: CorrectName="Oversized Product Details"
		 Case 53: CorrectName="Option 1"
		 Case 54: CorrectName="Attributes 1"
		 Case 55: CorrectName="Option 1 Required"
		 Case 56: CorrectName="Option 2"
		 Case 57: CorrectName="Attributes 2"
		 Case 58: CorrectName="Option 2 Required"
		 
		 '**** Apparel Product Fields: 59 - 67
		 
		 Case 68: CorrectName="Force purchase of multiples of minimum"
		 
		 'Start SDBA
		 Case 69: CorrectName="Product Cost"
		 Case 72: CorrectName="Back Order"
		 Case 73: CorrectName="Ship within N Days"
		 Case 74: CorrectName="Low inventory notification"
		 Case 75: CorrectName="Reorder Level"
		 Case 76: CorrectName="Is Drop-shipped"
		 Case 77: CorrectName="Supplier ID"
		 Case 78: CorrectName="Drop-Shipper ID"
		 Case 79: CorrectName="Drop-Shipper is also a Supplier"
		 'End SDBA
		 
			Case 80: CorrectName="Option 1 Order"
			Case 81: CorrectName="Option 2 Order"
			Case 82: CorrectName="Option 3"
			Case 83: CorrectName="Attributes 3"
			Case 84: CorrectName="Option 3 Required"
			Case 85: CorrectName="Option 3 Order"
			Case 86: CorrectName="Option 4"
			Case 87: CorrectName="Attributes 4"
			Case 88: CorrectName="Option 4 Required"
			Case 89: CorrectName="Option 4 Order"
			Case 90: CorrectName="Option 5"
			Case 91: CorrectName="Attributes 5"
			Case 92: CorrectName="Option 5 Required"
			Case 93: CorrectName="Option 5 Order"
			Case 94: CorrectName="Downloadable Product"
			Case 95: CorrectName="Gift Certificate"
			Case 96: CorrectName="Gift Certificate Expiration"
			Case 97: CorrectName="Electronic Only (Gift Certificate)"
			Case 98: CorrectName="Use Generator (Gift Certificate)"
			Case 99: CorrectName="Expiration Date (Gift Certificate)"
			Case 100: CorrectName="Expire N days (Gift Certificate)"
			Case 101: CorrectName="Custom Generator Filename (Gift Certificate)"
			Case 102: CorrectName="Hide BTO Price"
			Case 103: CorrectName="Hide Default Configuration"
			Case 104: CorrectName="Disallow purchasing"
			Case 105: CorrectName="Skip Product Details Page"
			Case 106: CorrectName="Short Category Description 1"
			Case 107: CorrectName="Long Category Description 1"
			Case 108: CorrectName="Category Small Image 1"
			Case 109: CorrectName="Category Large Image 1"
			Case 110: CorrectName="Short Category Description 2"
			Case 111: CorrectName="Long Category Description 2"
			Case 112: CorrectName="Category Small Image 2"
			Case 113: CorrectName="Category Large Image 2"
			Case 114: CorrectName="Mega Tags - Title"
			Case 115: CorrectName="Mega Tags - Description"
			Case 116: CorrectName="Mega Tags - Keywords"
			Case 117: CorrectName="Featured"
			Case 118: CorrectName="Units to make 1 lb"
			Case 119: CorrectName="First Unit Surcharge"
			Case 120: CorrectName="Additional Unit(s) Surcharge"
			
			Case 121: CorrectName="Product Notes"
			Case 122: CorrectName="Enable Image Magnifier"
			Case 123: CorrectName="Page Layout"
			Case 124: CorrectName="Hide SKU on the product details page"
			
			Case 125: CorrectName="Google Product Category"
			Case 126: CorrectName="Google Shopping - Gender"
			Case 127: CorrectName="Google Shopping - Age"
			Case 128: CorrectName="Google Shopping - Color"
			Case 129: CorrectName="Google Shopping - Size"
			Case 130: CorrectName="Google Shopping - Pattern"
			Case 131: CorrectName="Google Shopping - Material"
		 
		 End Select
	 
		 exit for
		
		end if
		 
		Next
		
		if CorrectName="" then
			Select Case ucase(trim(FDName))
			
			Case "SKU": CorrectName="SKU"
			Case "NAME": CorrectName="Name"
			Case "DESCRIPTION": CorrectName="Description"
			Case "SHORT DESCRIPTION": CorrectName="Short Description"
			Case "PRODUCT TYPE": CorrectName="Product Type"
			Case "ONLINE PRICE": CorrectName="Online Price"
			Case "LIST PRICE": CorrectName="List Price"
			Case "WHOLESALE PRICE": CorrectName="Wholesale Price"
			Case "WEIGHT": CorrectName="Weight"
			Case "STOCK": CorrectName="Stock"
			Case "CATEGORY NAME": CorrectName="Category Name"
			Case "CATEGORY SMALL IMAGE": CorrectName="Category Small Image"
			Case "CATEGORY LARGE IMAGE": CorrectName="Category Large Image"
			Case "PARENT CATEGORY": CorrectName="Parent Category"
			Case "ADDITIONAL CATEGORY 1": CorrectName="Additional Category 1"
			Case "PARENT CATEGORY 1": CorrectName="Parent Category 1"
			Case "ADDITIONAL CATEGORY 2": CorrectName="Additional Category 2"
			Case "PARENT CATEGORY 2": CorrectName="Parent Category 2"
			Case "BRAND NAME": CorrectName="Brand Name"
			Case "BRAND LOGO": CorrectName="Brand Logo"
			Case "THUMBNAIL IMAGE": CorrectName="Thumbnail Image"
			Case "GENERAL IMAGE": CorrectName="General Image"
			Case "DETAIL VIEW IMAGE": CorrectName="Detail view Image"
			Case "ACTIVE": CorrectName="Active"
			Case "SHOW SAVINGS": CorrectName="Show savings"
			Case "SPECIAL": CorrectName="Special"
			Case "NON-TAXABLE": CorrectName="Non-taxable"
			Case "NO SHIPPING CHARGE": CorrectName="No shipping charge"
			Case "NOT FOR SALE": CorrectName="Not for sale"
			Case "NOT FOR SALE COPY": CorrectName="Not for sale copy"
			Case "DISREGARD STOCK": CorrectName="Disregard stock"
			Case "DISPLAY NO SHIPPING TEXT": CorrectName="Display No Shipping Text"
			Case "CUSTOM SEARCH FIELD (1)": CorrectName="Custom Search Field (1)"
			Case "CUSTOM SEARCH FIELD (2)": CorrectName="Custom Search Field (2)"
			Case "CUSTOM SEARCH FIELD (3)": CorrectName="Custom Search Field (3)"
			Case "DOWNLOADABLE FILE LOCATION": CorrectName="Downloadable File Location"
			Case "MAKE DOWNLOAD URL EXPIRE": CorrectName="Make Download URL expire"
			Case "URL EXPIRATION IN DAYS": CorrectName="URL Expiration in Days"
			Case "USE LICENSE GENERATOR": CorrectName="Use License Generator"
			Case "LOCAL GENERATOR": CorrectName="Local Generator"
			Case "REMOTE GENERATOR": CorrectName="Remote Generator"
			Case "LICENSE FIELD LABEL (1)": CorrectName="License Field Label (1)"
			Case "LICENSE FIELD LABEL (2)": CorrectName="License Field Label (2)"
			Case "LICENSE FIELD LABEL (3)": CorrectName="License Field Label (3)"
			Case "LICENSE FIELD LABEL (4)": CorrectName="License Field Label (4)"
			Case "LICENSE FIELD LABEL (5)": CorrectName="License Field Label (5)"
			Case "ADDITIONAL COPY": CorrectName="Additional copy"
			Case "SHORT CATEGORY DESCRIPTION": CorrectName="Short Category Description"
			Case "LONG CATEGORY DESCRIPTION": CorrectName="Long Category Description"
			Case "MINIMUM QUANTITY CUSTOMERS CAN BUY": CorrectName="Minimum Quantity customers can buy"
			Case "REWARD POINTS": CorrectName="Reward Points"
			Case "OVERSIZED PRODUCT DETAILS": CorrectName="Oversized Product Details"
			Case "OPTION 1": CorrectName="Option 1"
			Case "ATTRIBUTES 1": CorrectName="Attributes 1"
			Case "OPTION 1 REQUIRED": CorrectName="Option 1 Required"
			Case "OPTION 2": CorrectName="Option 2"
			Case "ATTRIBUTES 2": CorrectName="Attributes 2"
			Case "OPTION 2 REQUIRED": CorrectName="Option 2 Required"
			
			'**** Apparel Product Fields: 59 - 67
			
			Case "FORCE PURCHASE OF MULTIPLES OF MINIMUM": CorrectName="Force purchase of multiples of minimum"
			
			'Start SDBA
			Case "PRODUCT COST": CorrectName="Product Cost"
			Case "BACK ORDER","BACK-ORDER": CorrectName="Back Order"
			Case "SHIP WITHIN N DAYS": CorrectName="Ship within N Days"
			Case "LOW INVENTORY NOTIFICATION": CorrectName="Low inventory notification"
			Case "REORDER LEVEL": CorrectName="Reorder Level"
			Case "IS DROP-SHIPPED": CorrectName="Is Drop-shipped"
			Case "SUPPLIER ID": CorrectName="Supplier ID"
			Case "DROP-SHIPPER ID": CorrectName="Drop-Shipper ID"
			Case "DROP-SHIPPER IS ALSO A SUPPLIER": CorrectName="Drop-Shipper is also a Supplier"
			'End SDBA
			
			Case "OPTION 1 ORDER": CorrectName="Option 1 Order"
			Case "OPTION 2 ORDER": CorrectName="Option 2 Order"
			Case "OPTION 3": CorrectName="Option 3"
			Case "ATTRIBUTES 3": CorrectName="Attributes 3"
			Case "OPTION 3 REQUIRED": CorrectName="Option 3 Required"
			Case "OPTION 3 ORDER": CorrectName="Option 3 Order"
			Case "OPTION 4": CorrectName="Option 4"
			Case "ATTRIBUTES 4": CorrectName="Attributes 4"
			Case "OPTION 4 REQUIRED": CorrectName="Option 4 Required"
			Case "OPTION 4 ORDER": CorrectName="Option 4 Order"
			Case "OPTION 5": CorrectName="Option 5"
			Case "ATTRIBUTES 5": CorrectName="Attributes 5"
			Case "OPTION 5 REQUIRED": CorrectName="Option 5 Required"
			Case "OPTION 5 ORDER": CorrectName="Option 5 Order"
			Case "DOWNLOADABLE PRODUCT": CorrectName="Downloadable Product"
			Case "GIFT CERTIFICATE": CorrectName="Gift Certificate"
			Case "GIFT CERTIFICATE EXPIRATION": CorrectName="Gift Certificate Expiration"
			Case "ELECTRONIC ONLY (GIFT CERTIFICATE)": CorrectName="Electronic Only (Gift Certificate)"
			Case "USE GENERATOR (GIFT CERTIFICATE)": CorrectName="Use Generator (Gift Certificate)"
			Case "EXPIRATION DATE (GIFT CERTIFICATE)": CorrectName="Expiration Date (Gift Certificate)"
			Case "EXPIRE N DAYS (GIFT CERTIFICATE)": CorrectName="Expire N days (Gift Certificate)"
			Case "CUSTOM GENERATOR FILENAME (GIFT CERTIFICATE)": CorrectName="Custom Generator Filename (Gift Certificate)"
			Case "HIDE BTO PRICE","HIDE BTO PRICES": CorrectName="Hide BTO Price"
			Case "HIDE DEFAULT CONFIGURATION": CorrectName="Hide Default Configuration"
			Case "DISALLOW PURCHASING": CorrectName="Disallow purchasing"
			Case "SKIP PRODUCT DETAILS PAGE": CorrectName="Skip Product Details Page"
			Case "SHORT CATEGORY DESCRIPTION 1": CorrectName="Short Category Description 1"
			Case "LONG CATEGORY DESCRIPTION 1": CorrectName="Long Category Description 1"
			Case "CATEGORY SMALL IMAGE 1": CorrectName="Category Small Image 1"
			Case "CATEGORY LARGE IMAGE 1": CorrectName="Category Large Image 1"
			Case "SHORT CATEGORY DESCRIPTION 2": CorrectName="Short Category Description 2"
			Case "LONG CATEGORY DESCRIPTION 2": CorrectName="Long Category Description 2"
			Case "CATEGORY SMALL IMAGE 2": CorrectName="Category Small Image 2"
			Case "CATEGORY LARGE IMAGE 2": CorrectName="Category Large Image 2"
			Case "MEGA TAGS - TITLE","META TAGS - TITLE": CorrectName="Mega Tags - Title"
			Case "MEGA TAGS - DESCRIPTION","META TAGS - DESCRIPTION": CorrectName="Mega Tags - Description"
			Case "MEGA TAGS - KEYWORDS","META TAGS - KEYWORDS": CorrectName="Mega Tags - Keywords"
			Case "FEATURED": CorrectName="Featured"
			Case "UNITS TO MAKE 1 LB": CorrectName="Units to make 1 lb"
			Case "FIRST UNIT SURCHARGE": CorrectName="First Unit Surcharge"
			Case "ADDITIONAL UNIT(S) SURCHARGE": CorrectName="Additional Unit(s) Surcharge"
			
			Case "PRODUCT NOTES": CorrectName="Product Notes"
			Case "ENABLE IMAGE MAGNIFIER": CorrectName="Enable Image Magnifier"
			Case "PAGE LAYOUT": CorrectName="Page Layout"
			Case "HIDE SKU ON THE PRODUCT DETAILS PAGE": CorrectName="Hide SKU on the product details page"
			
			Case "GOOGLE PRODUCT CATEGORY": CorrectName="Google Product Category"
			Case "Google Shopping - GENDER": CorrectName="Google Shopping - Gender"
			Case "Google Shopping - AGE": CorrectName="Google Shopping - Age"
			Case "Google Shopping - COLOR": CorrectName="Google Shopping - Color"
			Case "Google Shopping - SIZE": CorrectName="Google Shopping - Size"
			Case "Google Shopping - PATTERN": CorrectName="Google Shopping - Pattern"
			Case "Google Shopping - MATERIAL": CorrectName="Google Shopping - Material"
			
			End Select
		end if
		
		CheckField=CorrectName
    	
	End Function
%>