<% select case ECHO_decline_code

	case "0001"
		declined_msg=" The card must be referred to the issuer before the transaction can be approved." 
	case "0003"
		declined_msg=" Invalid merchant number. The merchant submitting the request is not supported by the acquirer."
	case "0004"
		declined_msg=" The card number has been listed on the Warning Bulletin File for reasons of counterfeit, fraud, or other."
	case "0005"
		declined_msg=" The transaction was declined by the issuer without definition or reason."
	case "0012"
		declined_msg=" Invalid transaction. The transaction request presented is not supported or is not valid for the card number presented."
	case "0013"
		declined_msg=" Invalid amount. The amount is below the minimum limit or above the maximum limit the issuer allows for this type of transaction."
	case "0014"
		declined_msg=" Invalid card number. The issuer has indicated this card number is not valid."
	case "0015"
		declined_msg=" Invalid issuer. The issuer number is not valid."
	case "0030"
		declined_msg=" Format error. The transaction was not formatted properly."
	case "0041"
		declined_msg=" Lost card. This card has been reported lost."
	case "0043"
		declined_msg=" Stolen card. This card has been reported stolen."
	case "0051"
		declined_msg=" Over credit limit. The transaction will result in an over credit limit or insufficient funds condition." 
	case "0054"
		declined_msg=" Expired card. The card has expired."
	case "0055"
		declined_msg=" Incorrect PIN. The cardholder-entered PIN is incorrect."
	case "0057"
		declined_msg=" Transaction not permitted. This card does not support the type of transaction requested."
	case "0058"
		declined_msg=" Transaction not permitted. The merchant's account does not support the type of transaction presented."
	case "0061"
		declined_msg=" Daily withdrawal limit exceeded. The cardholder has requested a withdrawal amount in excess of the daily defined maximum."
	case "0062"
		declined_msg=" Restricted card. The card has been restricted."
	case "0063"
		declined_msg=" Security violation. The card has been restricted."
	case "0065"
		declined_msg=" Withdrawal limit exceeded. The allowed number of daily transactions has been exceeded."
	case "0075"
		declined_msg=" Pin retries exceeded. The allowed number of PIN retries has been exceeded."
	case "0076"
		declined_msg=" Invalid ""to"" account. The ""to"" (credit) account specified in the transaction does not exist or is not associated with the card number presented."
	case "0077"
		declined_msg=" Invalid ""from"" account. The ""from"" (debit) account specified in the transaction does not exist or is not associated with the card number presented."
	case "0078"
		declined_msg=" Invalid account. The ""from"" (debit) or ""to"" (credit) account does not exist or is not associated with the card number presented."
	case "0084"
		declined_msg=" Invalid cycle. The authorization life cycle is above or below limits established by the issuer."
	case "0091"
		declined_msg=" Issuer not available. The bank is not available to authorize this transaction."
	case "0092"
		declined_msg=" The transaction does not contain enough information to be routed to the authorizing agency."
	case "0094"
		declined_msg=" Duplicate transmission. The host has detected a duplicate transmission."
	case "0096"
		declined_msg=" Authorization system error. A system error has occurred or the files required for authorization are not available. "
	case "1000"
		declined_msg=" Unrecoverable error. An unrecoverable error has occurred in the ECHONLINE processing."
	case "1001"
		declined_msg=" Account closed. The merchant account has been closed."
	case "1002"
		declined_msg=" System closed. Services for this system are not available at this time."
	case "1003"
		declined_msg=" E-Mail Down. The e-mail function is not available at this time."
	case "1012"
		declined_msg=" Invalid transaction code. The host computer received an invalid transaction code."
	case "1013"
		declined_msg=" The ECHO-ID is invalid."
	case "1015"
		declined_msg=" Invalid card number. The credit card number provided for this transaction is not valid."
	case "1016"
		declined_msg=" Invalid expiration date. The card has expired or the expiration date is not valid."
	case "1017"
		declined_msg=" Invalid order amount. The dollar amount was less than 1.00 or greater than the maximum allowed for this card."
	case "1019"
		declined_msg=" The state code was invalid."
	case "1021"
		declined_msg=" The merchant or card holder is not allowed to perform this transaction."
	case "1024"
		declined_msg=" Invalid authorization code. The authorization number presented with this transaction is incorrect."
	case "1025"
		declined_msg=" Invalid reference number. The reference number presented with this transaction is incorrect or is not numeric."
	case "1029"
		declined_msg=" Invalid contract number. The contract number presented with this transaction is incorrect or is not numeric."
	case "1030"
		declined_msg=" Invalid inventory data. The inventory data presented with this transaction is not ASCII ""printable""."
	case "1508"
		declined_msg=" Invalid or missing order_type."
	case "1509"
		declined_msg=" The merchant is not approved to submit this order_type."
	case "1510"
		declined_msg=" The merchant is not approved to submit this transaction_type."
	case "1511"
		declined_msg=" Duplicate transaction attempt."
	case "1599"
		declined_msg=" An system error occurred while validating the transaction input."
	case "1801"
		declined_msg=" Address verification problem. The address matches, the ZIP code does not match."
	case "1802"
		declined_msg=" Address verification problem. 9-digit ZIP matches, address does not match."
	case "1803"
		declined_msg=" Address verification problem. 5-digit ZIP matches, address does not match."
	case "1804"
		declined_msg=" Issuer unavailable; cannot verify."
	case "1805"
		declined_msg=" The system is currently unable to process. Please try again."
	case "1806"
		declined_msg=" Issuer does not support AVS (Address verification)."
	case "1807"
		declined_msg=" Address verification problem. Nothing matches."
	case "1808"
		declined_msg=" Invalid AVS only response."
	case "1809"
		declined_msg=" Street address match. Postal code not verified because of incompatible formats."
	case "1810"
		declined_msg=" Street address and Postal code not verified because of incompatible formats."
	case "1811"
		declined_msg=" Street address match and Postal code match."
	case "1812"
		declined_msg=" Address information not verified for international transaction."
	case "1813"
		declined_msg=" Street address match and Postal code match."
	case "1814"
		declined_msg=" Postal code match. Street address not verified because of incompatible formats."
	case "1897"
		declined_msg=" Invalid response. The host returned an invalid response."
	case "1898"
		declined_msg=" The host unexpectedly disconnected."
	case "1899"
		declined_msg=" The transaction timed out while waiting for a response."
	case "2071"
		declined_msg=" Call VISA. An authorization number from the VISA Voice Center is required to approve this transaction."
	case "2072"
		declined_msg=" Call MasterCard. An authorization number from the Master Card Voice Center is required to approve this transaction."
	case "2073"
		declined_msg=" Call Carte Blanche. An authorization number from the Carte Blanche Voice Center is required to approve this transaction."
	case "2074"
		declined_msg=" Call Diners Club. An authorization number from the Diners Club Voice Center is required to approve this transaction."
	case "2075"
		declined_msg=" Call AMEX. An authorization number from the American Express Voice Center is required to approve this transaction."
	case "2076"
		declined_msg=" Call Discover. An authorization number from the Discover Voice Center is required to approve this transaction."
	case "2078"
		declined_msg=" Call ECHO. The merchant must call ECHO Customer Support for approval or because there is a problem with the merchant account."
	case "2079"
		declined_msg=" Call XpresscheX. The merchant must call ECHO Customer Support for approval.or because there is a problem with the merchant account."
		
end select
%>