<%

'--------------------------------------------------------------------
' USA ePay
'
' XCharge constants include file for VBScript
'--------------------------------------------------------------------

'---- CommandType Values ----
const sale = 0
const credit = 1
const cvoid = 2
const authonly = 3
const capture = 4
const postauth = 5
const check = 6
const checkcredit = 7

'---- ScheduleType Values ----
const daily = 0
const weekly = 1
const biweekly = 2
const monthly = 3
const bimonthly = 4
const quarterly = 5
const annually = 6
const biannually = 7

'---- StatusType Values ----
const Approved = 0
const Declined = 1
const Verification = 2
const Error = 3

'---- CptTermTypeType ----
const pos = 0
const StandAlone = 1
const Unattended = 2
const TermTypeUnknown = 3

'---- CptMagSupportType ----
const MagSupportYes = 0
const MagSupportNo = 1
const MagSupportUnknown = 2

%>

