<table border="0" width="100%" cellpadding="0" cellspacing="0">
<tr><td valign="top">&nbsp;</td><td width="100%" valign="top" class="">&nbsp;<a href="viewCategories.asp?idCategory=3">Cats</a>
</td></tr>
<tr><td valign="top">&nbsp;</td><td width="100%" valign="top" class="">&nbsp;<a href="viewCategories.asp?idCategory=2">Dogs</a>
</td></tr>
<tr><td valign="top">&nbsp;</td><td width="100%" valign="top" class="">&nbsp;<a href="viewCategories.asp?idCategory=4">Horses</a>
</td></tr>
<tr><td valign="top">&nbsp;</td><td width="100%" valign="top" class="">&nbsp;<a href="viewCategories.asp?idCategory=5">Livestock Show Animals</a>
</td></tr>
</table>