<%
Function USPSCountry(cntry)

Select Case cntry
Case "AL"
	Country="Albania" 
Case "DZ"
	Country="Algeria" 
Case "AS"
	Country="American Samoa" 
Case "AD"
	Country="Andorra" 
Case "AF"
	Country="Afghanistan" 
Case "AI"
	Country="Anguilla" 
Case "AG"
	Country="Antigua and Barbuda" 
Case "AM"
	Country="Armenia" 
Case "AO"
	Country="Angola" 
Case "AQ"
	Country="Antarctica" 
Case "AR"
	Country="Argentina" 
Case "AW"
	Country="Aruba" 
Case "AU"
	Country="Australia" 
Case "AT"
	Country="Austria" 
Case "AX"
	Country="Aland Island" 
Case "AZ"
	Country="Azerbaijan" 
Case "BH"
	Country="Bahrain" 
Case "BD"
	Country="Bangladesh" 
Case "BB"
	Country="Barbados" 
Case "BE"
	Country="Belgium" 
Case "BZ"
	Country="Belize" 
Case "BY"
	Country="Belarus" 
Case "BJ"
	Country="Benin" 
Case "BM"
	Country="Bermuda" 
Case "BO"
	Country="Bolivia" 
Case "BT"
	Country="Bhutan" 
Case "BA"
	Country="Bosnia-Herzegovina" 
Case "BW"
	Country="Botswana" 
Case "BR"
	Country="Brazil" 
Case "VG"
	Country="Virgin Islands, British" 
Case "IO"
	Country="British Indian Ocean" 
Case "BN"
	Country="Brunei Darussalam" 
Case "BG"
	Country="Bulgaria" 
Case "BF"
	Country="Burkina Faso" 
Case "BI"
	Country="Burundi" 
Case "BV"
	Country="Bouvet Island" 
Case "KH"
	Country="Cambodia" 
Case "CM"
	Country="Cameroon" 
Case "CA"
	Country="Canada" 
Case "IC"
	Country="Spain" 
Case "CV"
	Country="Cape Verde" 
Case "KY"
	Country="Cayman Islands" 
Case "CF"
	Country="Central African Republic" 
Case "TD"
	Country="Chad" 
Case "CL"
	Country="Chile" 
Case "CN"
	Country="China" 
Case "CX"
	Country="Christmas Island" 
Case "CO"
	Country="Colombia" 
Case "CC"
	Country="Cocos (Keeling) Islands" 
Case "KM"
	Country="Comoros" 
Case "CD"
	Country="Congo, Democratic Republic of the" 
Case "CG"
	Country="Congo" 
Case "CK"
	Country="Cook Islands" 
Case "CR"
	Country="Costa Rica" 
Case "HR"
	Country="Croatia" 
Case "CY"
	Country="Cyprus" 
Case "CU"
	Country="Cuba" 
Case "CZ"
	Country="Czech Republic" 
Case "DK"
	Country="Denmark" 
Case "DJ"
	Country="Djibouti" 
Case "DM"
	Country="Dominica" 
Case "DO"
	Country="Dominican Republic" 
Case "EC"
	Country="Ecuador" 
Case "EG"
	Country="Egypt" 
Case "SV"
	Country="El Salvador" 
Case "EN"
	Country="Great Britain and Northern Ireland" 
Case "GQ"
	Country="Equatorial Guinea" 
Case "ER"
	Country="Eritrea" 
Case "EE"
	Country="Estonia" 
Case "ET"
	Country="Ethiopia" 
Case "FO"
	Country="Faeroe Islands" 
Case "FK"
	Country="Falkland Islands (Malvinas)" 
Case "FM"
	Country="Micronesia, Federated States of" 
Case "FJ"
	Country="Fiji" 
Case "FI"
	Country="Finland" 
Case "FR"
	Country="France" 
Case "TF"
	Country="French Southern Territories" 
Case "GF"
	Country="French Guiana" 
Case "PF"
	Country="French Polynesia" 
Case "GA"
	Country="Gabon" 
Case "GM"
	Country="Gambia" 
Case "GE"
	Country="Georgia" 
Case "DE"
	Country="Germany" 
Case "GH"
	Country="Ghana" 
Case "GI"
	Country="Gibraltar" 
Case "GR"
	Country="Greece" 
Case "GL"
	Country="Greenland" 
Case "GD"
	Country="Grenada" 
Case "GP"
	Country="Guadeloupe" 
Case "GG"
	Country="Guernsey" 
Case "GU"
	Country="Guam" 
Case "GT"
	Country="Guatemala" 
Case "GN"
	Country="Guinea" 
Case "GW"
	Country="Guinea-Bissau" 
Case "GY"
	Country="Guyana" 
Case "HT"
	Country="Haiti" 
Case "HO"
	Country="Holland" 
Case "HM"
	Country="Heard Island and McDonald" 
Case "HN"
	Country="Honduras" 
Case "HK"
	Country="Hong Kong" 
Case "HU"
	Country="Hungary" 
Case "IS"
	Country="Iceland" 
Case "IN"
	Country="India" 
Case "ID"
	Country="Indonesia" 
Case "IR"
	Country="Iran" 
Case "IQ"
	Country="Iraq" 
Case "IE"
	Country="Ireland" 
Case "IL"
	Country="Israel" 
Case "IM"
	Country="Isle of Man" 
Case "IT"
	Country="Italy" 
Case "CI"
	Country="Cote d lvoire (Ivory Coast)" 
Case "JM"
	Country="Jamaica" 
Case "JP"
	Country="Japan" 
Case "JE"
	Country="Jersey" 
Case "JO"
	Country="Jordan" 
Case "KZ"
	Country="Kazakhstan" 
Case "KE"
	Country="Kenya" 
Case "KI"
	Country="Kiribati" 
Case "KO"
	Country="US Possession" 
Case "KW"
	Country="Kuwait" 
Case "KG"
	Country="Kyrgyzstan" 
Case "LA"
	Country="Lao People's Democratic Republic"
Case "LV"
	Country="Latvia" 
Case "LB"
	Country="Lebanon" 
Case "LS"
	Country="Lesotho" 
Case "LR"
	Country="Liberia" 
Case "LY"
	Country="Libyan Arab Jamahiriya" 
Case "LI"
	Country="Liechtenstein" 
Case "LT"
	Country="Lithuania" 
Case "LU"
	Country="Luxembourg" 
Case "MO"
	Country="Macao" 
Case "MK"
	Country="Macedonia" 
Case "MG"
	Country="Madagascar" 
Case "ME"
	Country="Madeira" 
Case "MW"
	Country="Malawi" 
Case "MY"
	Country="Malaysia" 
Case "MV"
	Country="Maldives" 
Case "ML"
	Country="Mali" 
Case "MT"
	Country="Malta" 
Case "MH"
	Country="Marshall Islands" 
Case "MQ"
	Country="Martinique" 
Case "MR"
	Country="Mauritania" 
Case "MU"
	Country="Mauritius" 
Case "YT"
	Country="Mayotte" 
Case "MX"
	Country="Mexico" 
Case "MD"
	Country="Moldova" 
Case "MC"
	Country="Monaco" 
Case "MN"
	Country="Mongolia" 
Case "MS"
	Country="Montserrat" 
Case "MA"
	Country="Morocco" 
Case "MZ"
	Country="Mozambique" 
Case "MM"
	Country="Myanmar" 
Case "NA"
	Country="Namibia" 
Case "NR"
	Country="Nauru" 
Case "NP"
	Country="Nepal" 
Case "NL"
	Country="Netherlands" 
Case "AN"
	Country="Netherlands Antilles" 
Case "NC"
	Country="New Caledonia" 
Case "NZ"
	Country="New Zealand" 
Case "NI"
	Country="Nicaragua" 
Case "NE"
	Country="Niger" 
Case "NG"
	Country="Nigeria" 
Case "NU"
	Country="Niue" 
Case "NF"
	Country="Norfolk Island" 
Case "NB"
	Country="Great Britain and Northern Ireland" 
Case "MP"
	Country="Northern Mariana Islands" 
Case "NO"
	Country="Norway" 
Case "OM"
	Country="Oman" 
Case "PK"
	Country="Pakistan" 
Case "PW"
	Country="Palau" 
Case "PS"
	Country="Palestinian Territory, Occupied" 
Case "PA"
	Country="Panama" 
Case "PG"
	Country="Papua New Guinea" 
Case "PY"
	Country="Paraguay" 
Case "PE"
	Country="Peru" 
Case "PH"
	Country="Philippines" 
Case "PN"
	Country="Pitcairn" 
Case "PL"
	Country="Poland" 
Case "PO"
	Country="Ponape" 
Case "PT"
	Country="Portugal" 
Case "PR"
	Country="Puerto Rico" 
Case "QA"
	Country="Qatar" 
Case "YE"
	Country="Yemen" 
Case "RE"
	Country="Reunion" 
Case "RO"
	Country="Romania" 
Case "RT"
	Country="US Possession" 
Case "RU"
	Country="Russia" 
Case "RW"
	Country="Rwanda" 
Case "SS"
	Country="Netherlands Antilles" 
Case "SP"
	Country="US Possession" 
Case "SH"
	Country="Saint Helena" 
Case "SA"
	Country="Saudi Arabia" 
Case "SM"
	Country="San Marino" 
Case "ST"
	Country="Sao Tome and Principe" 
Case "SF"
	Country="Great Britain and Northern Ireland" 
Case "SN"
	Country="Senegal" 
Case "SC"
	Country="Seychelles" 
Case "CS"
	Country="Serbia and Montenegro" 
Case "SL"
	Country="Sierra Leone" 
Case "SG"
	Country="Singapore" 
Case "SK"
	Country="Slovakia" 
Case "SI"
	Country="Slovenia" 
Case "SB"
	Country="Solomon Islands" 
Case "SO"
	Country="Somalia" 
Case "GS"
	Country="South Georgia and the Sandwich Islands" 
Case "ZA"
	Country="South Africa" 
Case "SJ"
	Country="Svalbard and Jan Mayen" 
Case "KR"
	Country="Korea, Republic of (South Korea)" 
Case "KP"
	Country="Korea, Democratic People's Republic of (North Korea)" 
Case "ES"
	Country="Spain"
Case "LK"
	Country="Sri Lanka" 
Case "NT"
	Country="St. Barthelemy" 
Case "SW"
	Country="St. Christopher and Nevis" 
Case "SX"
	Country="US Possession" 
Case "EU"
	Country="Netherlands Antilles" 
Case "UV"
	Country="US Possession" 
Case "KN"
	Country="St. Kitts and Nevis" 
Case "LC"
	Country="St. Lucia" 
Case "PM"
	Country="St. Pierre and Miquelon" 
Case "MB"
	Country="Netherlands Antilles" 
Case "TB"
	Country="Guadeloupe" 
Case "VL"
	Country="US Possession" 
Case "VC"
	Country="St. Vincent and the Grenadines" 
Case "SD"
	Country="Sudan" 
Case "SR"
	Country="Suriname" 
Case "SZ"
	Country="Swaziland" 
Case "SE"
	Country="Sweden" 
Case "CH"
	Country="Switzerland" 
Case "SY"
	Country="Syrian Arab Republic" 
Case "TA"
	Country="French Polynesia" 
Case "TW"
	Country="Taiwan" 
Case "TJ"
	Country="Tajikistan" 
Case "TZ"
	Country="Tanzania, United Republic of" 
Case "TH"
	Country="Thailand" 
Case "TI"
	Country="US Possession" 
Case "TG"
	Country="Togo" 
Case "TK"
	Country="Tokelau" 
Case "TO"
	Country="Tonga" 
Case "TL"
	Country="Timor-Leste" 
Case "TT"
	Country="Trinidad and Tobago" 
Case "TU"
	Country="US Possession" 
Case "TN"
	Country="Tunisia" 
Case "TR"
	Country="Turkey" 
Case "TC"
	Country="Turks and Caicos Islands" 
Case "TM"
	Country="Turkmenistan" 
Case "TV"
	Country="Tuvalu" 
Case "UG"
	Country="Uganda" 
Case "UA"
	Country="Ukraine" 
Case "UI"
	Country="Union Island" 
Case "AE"
	Country="United Arab Emirates" 
Case "GB"
	Country="Great Britain and Northern Ireland" 
Case "US"
	Country="United States" 
Case "UM"
	Country="United States Minor Outlying Islands" 
Case "UY"
	Country="Uruguay" 
Case "VI"
	Country="Virgin Islands, US" 
Case "UZ"
	Country="Uzbekistan" 
Case "VU"
	Country="Vanuatu" 
Case "VE"
	Country="Venezuela" 
Case "VN"
	Country="Vietnam" 
Case "VR"
	Country="Virgin Gorda" 
Case "WK"
	Country="US Possession" 
Case "WL"
	Country="Great Britain and Northern Ireland" 
Case "WF"
	Country="Wallis and Futuna Islands" 
Case "WS"
	Country="Samoa" 
Case "EH"
	Country="Western Sahara" 
Case "YA"
	Country="US Possession" 
Case "YU"
	Country="Yugoslavia" 
Case "ZM"
	Country="Zambia" 
Case "ZW"
	Country="Zimbabwe" 
Case Else
	Country="**"
End Select

if Country <> "**" and Country <> "Error" then
	USPSCountry=Country
else
	USPSCountry=""
end if

End Function
%>
