<%
'This file is part of ProductCart, an ecommerce application developed and sold by NetSource Commerce. ProductCart, its source code, the ProductCart name and logo are property of NetSource Commerce. Copyright 2001-2013. All rights reserved. You are not allowed to use, alter, distribute and/or resell any parts of ProductCart's source code without the written consent of NetSource Commerce. To contact NetSource Commerce, please visit www.productcart.com.
%>
<% response.Buffer=true %>
<%PmAdmin=9%><!--#include file="adminv.asp"--> 
<!--#include file="../includes/languages.asp"--> 
<!--#include file="../includes/settings.asp"-->
<!--#include file="../includes/storeconstants.asp"-->
<!--#include file="../includes/opendb.asp"-->
<!--#include file="../includes/SQLFormat.txt"-->
<!--#include file="../includes/ErrorHandler.asp"-->
<!--#include file="../includes/stringfunctions.asp"-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>Modify Shipment Information</title>
	<link href="pcv4_ControlPanel.css" rel="stylesheet" type="text/css">
</head>
<body style="background-image: none;">

<% dim conntemp, query, rs

'//USPS Variables
call opendb()

query="SELECT active, shipServer, userID FROM ShipmentTypes WHERE idshipment=4;"
set rs=server.CreateObject("ADODB.RecordSet")
set rs=conntemp.execute(query)
if err.number<>0 then
	call LogErrorToDatabase()
	set rs=nothing
	call closedb()
	response.redirect "techErr.asp?err="&pcStrCustRefID
end if
pcv_USPSUserID=trim(rs("userID"))
pcv_USPSShipServer=trim(rs("shipserver"))
pcv_USPSActive=rs("active")

set rs=nothing
call closedb()

Dim pageTitle, Section
pageTitle="View &amp; Process Order"
Section="orders"

pcv_TrackingNumber=request("TN")
'TO REMOVE
pcv_USPSShipServer="http://production.shippingapis.com/ShippingAPI.dll"
'pcv_USPSUserID="467EARLY3087"


usps_postdata=""
usps_postdata=usps_postdata&pcv_USPSShipServer&"?API=TrackV2&XML="
usps_postdata=usps_postdata&"<TrackFieldRequest USERID="&chr(34)&pcv_USPSUserID&chr(34)&">"
usps_postdata=usps_postdata&"<TrackID ID="&chr(34)&pcv_TrackingNumber&chr(34)&"></TrackID>"
usps_postdata=usps_postdata&"</TrackFieldRequest>"

err.clear
Set srvUSPS2XmlHttp = server.createobject("Msxml2.serverXmlHttp"&scXML)
srvUSPS2XmlHttp.open "GET", usps_postdata, false
srvUSPS2XmlHttp.send
USPS2_result = srvUSPS2XmlHttp.responseText

Set srvUPSXmlHttp = server.createobject("Msxml2.serverXmlHttp")'&scXML)
Set objOutputXMLDoc = Server.CreateObject("Microsoft.XMLDOM")
Set objUPSStream = Server.CreateObject("ADODB.Stream")
Set objUPSXmlDoc = server.createobject("Msxml2.DOMDocument")'&scXML)
objUPSXmlDoc.async = False
objUPSXmlDoc.validateOnParse = False

objOutputXMLDoc.loadXML USPS2_result

'// Error Check
strErrorNumber=""
strErrorDescription=""

Set LNodes = objOutputXMLDoc.selectNodes("//Error")
intLNode=0
For Each LNode In LNodes
	strErrorNumber=LNode.selectSingleNode("Number").Text			'Number = the error number generated by the Web Tools server.
	strErrorSource=LNode.selectSingleNode("Source").Text			'Source = the component and interface that generated the error on the Web Tools server.
	strErrorDescription=LNode.selectSingleNode("Description").Text	'Description = the error description.
	strErrorHelpFile=LNode.selectSingleNode("HelpFile").Text		'HelpFile = [reserved for future use].
	strErrorHelpContext=LNode.selectSingleNode("HelpContext").Text	'HelpContext = [reserved for future use].
Next

if strErrorNumber="" AND strErrorDescription="" then
	on error resume next
	Set Nodes = objOutputXMLDoc.selectNodes("//TrackSummary")
	For Each Node In Nodes
		pcv_TrackInfo_EventTime=Node.selectSingleNode("EventTime").Text  	
		pcv_TrackInfo_EventDate=Node.selectSingleNode("EventDate").Text  	
		pcv_TrackInfo_Event=Node.selectSingleNode("Event").Text  	
		pcv_TrackInfo_EventCity=Node.selectSingleNode("EventCity").Text  	
		pcv_TrackInfo_EventState=Node.selectSingleNode("EventState").Text  	
		pcv_TrackInfo_EventZIPCode=Node.selectSingleNode("EventZIPCode").Text  	
		pcv_TrackInfo_EventCountry=Node.selectSingleNode("EventCountry").Text  	
		pcv_TrackInfo_FirmName=Node.selectSingleNode("FirmName").Text  	
		pcv_TrackInfo_Name=Node.selectSingleNode("Name").Text  	
		pcv_TrackInfo_AuthorizedAgent=Node.selectSingleNode("AuthorizedAgent").Text  	
	Next
	
	
	strTrackSummary = ""
    	strTrackSummary=strTrackSummary&"<tr><td colspan='2'>"&pcv_TrackInfo_Event&", "&pcv_TrackInfo_EventDate&", "&pcv_TrackInfo_EventTime&", "&pcv_TrackInfo_EventCity&", "&pcv_TrackInfo_EventState&" "&pcv_TrackInfo_EventZIPCode&" </td></tr>"
	strTrackDetails=""

	
	Set Nodes = objOutputXMLDoc.selectNodes("//TrackDetail")
	For Each Node In Nodes
		'pcv_TrackInfo_TrackSummary=Node.selectSingleNode("TrackSummary").Text  
		'pcv_TrackInfo_TrackDetail=Node.selectSingleNode("TrackDetail").Text  
		pcv_EventTime=Node.selectSingleNode("EventTime").Text  	
		pcv_EventDate=Node.selectSingleNode("EventDate").Text  	
		pcv_Event=Node.selectSingleNode("Event").Text  	
		pcv_EventCity=Node.selectSingleNode("EventCity").Text  	
		pcv_EventState=Node.selectSingleNode("EventState").Text  	
		pcv_EventZipCode=Node.selectSingleNode("EventZIPCode").Text  	
		'response.write "<BR>"&Node.selectSingleNode("EventCountry").Text  	
		'response.write "<BR>"&Node.selectSingleNode("FirmName").Text  	
		'response.write "<BR>"&Node.selectSingleNode("Name").Text  	
		'response.write "<BR>"&Node.selectSingleNode("AuthorizedAgent").Text  	
    	strTrackDetails=strTrackDetails&"<tr><td colspan='2'>"&pcv_Event&", "&pcv_EventDate&", "&pcv_EventTime&", "&pcv_EventCity&", "&pcv_EventState&" "&pcv_EventZipCode&" </td></tr>"
	Next

	set objLst=objOutputXMLDoc.getElementsByTagName("TrackInfo")
	'response.write objLst.length
	for i = 0 to (objLst.length - 1)
		for j=0 to ((objLst.item(i).childNodes.length)-1)
			If objLst.item(i).childNodes(j).nodeName="TrackDetail" then
				pcv_TrackInfo_TrackDetail2=pcv_TrackInfo_TrackDetail2&"<BR>"&objLst.item(i).childNodes(j).Text
			End if
		next
	next
	%>

    <table width="391" class="pcCPcontent">
        <tr>
            <th colspan="2">USPS Tracking information:</th>
        </tr>
        <tr>
            <td colspan="2" class="pcCPspacer"></td>
        </tr>
        <tr>
          <td width="131"><strong>Label/Receipt Number:</strong></td>
          <td width="248"><%=pcv_TrackingNumber%></td>
        </tr>
        <tr>
            <td colspan="2" class="pcCPspacer"></td>
        </tr>
        <tr>
          <td><strong>Summary:</strong></td>
          <td><p>&nbsp;</p></td>
        </tr>
        <%=strTrackSummary%>
        <%=strTrackDetails%>
        <tr>
            <td colspan="2" class="pcCPspacer"></td>
        </tr>
        <tr>
            <td colspan="2" align="center"><input type="button" name="Close Window" value="Close Window" onClick="javascript:window.close();" /></td>
        </tr>
    </table>
<% else %>
    <table width="391" class="pcCPcontent">
        <tr>
            <th colspan="2">USPS Tracking information:</th>
        </tr>
        <tr>
            <td colspan="2" class="pcCPspacer"></td>
        </tr>
        <tr>
          <td width="131"><strong>Label/Receipt Number:</strong></td>
          <td width="248"><%=pcv_TrackingNumber%></td>
        </tr>
        <tr>
            <td colspan="2" class="pcCPspacer"></td>
        </tr>
        <tr>
          <td><strong>Error:</strong></td>
          <td><p><%=strErrorDescription%></p></td>
        </tr>
        <tr>
            <td colspan="2" class="pcCPspacer"></td>
        </tr>
        <tr>
            <td colspan="2" align="center"><input type="button" name="Close Window" value="Close Window" onClick="javascript:window.close();" /></td>
        </tr>
    </table>
<% end if %>
</body>
</html>
