<%
'// ProductCart Control Panel
'// Text strings

if session("language")="" then
	session("language")="english"
end if

dim dictLanguageCP
set dictLanguageCP=CreateObject("Scripting.Dictionary")

'///////////////////////////////////////
'// 					ENGLISH 								//
'///////////////////////////////////////

'// Frequently used strings

dictLanguageCP.Add "english_cpCommon_1", "Date"
dictLanguageCP.Add "english_cpCommon_2", "Store Name"
dictLanguageCP.Add "english_cpCommon_3", "Address"
dictLanguageCP.Add "english_cpCommon_4", "Customer"
dictLanguageCP.Add "english_cpCommon_5", "Customers"
dictLanguageCP.Add "english_cpCommon_6", "Customer Type:"
dictLanguageCP.Add "english_cpCommon_7", "Retail"
dictLanguageCP.Add "english_cpCommon_8", "Wholesale"
dictLanguageCP.Add "english_cpCommon_9", "First Name"
dictLanguageCP.Add "english_cpCommon_10", "Last Name"
dictLanguageCP.Add "english_cpCommon_11", "Name"
dictLanguageCP.Add "english_cpCommon_12", "Company"
dictLanguageCP.Add "english_cpCommon_13", "Phone"
dictLanguageCP.Add "english_cpCommon_14", "Fax"
dictLanguageCP.Add "english_cpCommon_15", "E-mail"
dictLanguageCP.Add "english_cpCommon_16", "User Name"
dictLanguageCP.Add "english_cpCommon_17", "Password"
dictLanguageCP.Add "english_cpCommon_18", "Billing Address "
dictLanguageCP.Add "english_cpCommon_19", "Shipping Address"
dictLanguageCP.Add "english_cpCommon_21", "Street"
dictLanguageCP.Add "english_cpCommon_22", "City"
dictLanguageCP.Add "english_cpCommon_23", "State"
dictLanguageCP.Add "english_cpCommon_24", "Country"
dictLanguageCP.Add "english_cpCommon_25", "Postal Code"

dictLanguageCP.Add "english_cpCommon_26", "SKU"
dictLanguageCP.Add "english_cpCommon_27", "Description"
dictLanguageCP.Add "english_cpCommon_28", "Name"
dictLanguageCP.Add "english_cpCommon_29", "Short Description"
dictLanguageCP.Add "english_cpCommon_30", "Online Price"
dictLanguageCP.Add "english_cpCommon_31", "List Price"
dictLanguageCP.Add "english_cpCommon_32", "Wholesale Price"
dictLanguageCP.Add "english_cpCommon_33", "Cost"
dictLanguageCP.Add "english_cpCommon_34", "Show Savings"
dictLanguageCP.Add "english_cpCommon_35", "Brand"
dictLanguageCP.Add "english_cpCommon_36", "Supplier"
dictLanguageCP.Add "english_cpCommon_36b", "Drop-Shipper"
dictLanguageCP.Add "english_cpCommon_37", "Active"
dictLanguageCP.Add "english_cpCommon_38", "Special"
dictLanguageCP.Add "english_cpCommon_39", "Featured"
dictLanguageCP.Add "english_cpCommon_40", "Weight"
dictLanguageCP.Add "english_cpCommon_41", "Height"
dictLanguageCP.Add "english_cpCommon_42", "Width"
dictLanguageCP.Add "english_cpCommon_43", "Length"

dictLanguageCP.Add "english_cpCommon_50", "Order"
dictLanguageCP.Add "english_cpCommon_51", "Orders"
dictLanguageCP.Add "english_cpCommon_52", "Order ID"
dictLanguageCP.Add "english_cpCommon_53", "Order #"
dictLanguageCP.Add "english_cpCommon_54", "Order Status"
dictLanguageCP.Add "english_cpCommon_55", "Google Order ID"

dictLanguageCP.Add "english_cpCommon_100", "Submit"
dictLanguageCP.Add "english_cpCommon_101", "Update"
dictLanguageCP.Add "english_cpCommon_102", "Back"
dictLanguageCP.Add "english_cpCommon_103", "Find Another Product"
dictLanguageCP.Add "english_cpCommon_104", "Manage Categories"
dictLanguageCP.Add "english_cpCommon_105", "Continue"
dictLanguageCP.Add "english_cpCommon_106", "Add New"
dictLanguageCP.Add "english_cpCommon_107", "Save Settings"


dictLanguageCP.Add "english_cpCommon_150", "Product"
dictLanguageCP.Add "english_cpCommon_151", "Products"
dictLanguageCP.Add "english_cpCommon_152", "Categories"
dictLanguageCP.Add "english_cpCommon_153", "Meta Tags"
dictLanguageCP.Add "english_cpCommon_154", "Title"
dictLanguageCP.Add "english_cpCommon_155", "Description"
dictLanguageCP.Add "english_cpCommon_156", "Keywords"
dictLanguageCP.Add "english_cpCommon_157", "Category Name"
dictLanguageCP.Add "english_cpCommon_158", "Parent Category"


dictLanguageCP.Add "english_cpCommon_201", "January"
dictLanguageCP.Add "english_cpCommon_202", "February"
dictLanguageCP.Add "english_cpCommon_203", "March"
dictLanguageCP.Add "english_cpCommon_204", "April"
dictLanguageCP.Add "english_cpCommon_205", "May"
dictLanguageCP.Add "english_cpCommon_206", "June"
dictLanguageCP.Add "english_cpCommon_207", "July"
dictLanguageCP.Add "english_cpCommon_208", "August"
dictLanguageCP.Add "english_cpCommon_209", "September"
dictLanguageCP.Add "english_cpCommon_210", "October"
dictLanguageCP.Add "english_cpCommon_211", "November"
dictLanguageCP.Add "english_cpCommon_212", "December"
dictLanguageCP.Add "english_cpCommon_220", "Monday"
dictLanguageCP.Add "english_cpCommon_221", "Tuesday"
dictLanguageCP.Add "english_cpCommon_222", "Wednesday"
dictLanguageCP.Add "english_cpCommon_223", "Thursday"
dictLanguageCP.Add "english_cpCommon_224", "Friday"
dictLanguageCP.Add "english_cpCommon_225", "Saturday"
dictLanguageCP.Add "english_cpCommon_226", "Sunday"
dictLanguageCP.Add "english_cpCommon_230", "Previous Years"
dictLanguageCP.Add "english_cpCommon_231", "Year Total"
dictLanguageCP.Add "english_cpCommon_232", "Monthly Sales"
dictLanguageCP.Add "english_cpCommon_233", "Format"
dictLanguageCP.Add "english_cpCommon_234", "DD/MM/YY"
dictLanguageCP.Add "english_cpCommon_235", "MM/DD/YY"


dictLanguageCP.Add "english_cpCommon_300", " by "
dictLanguageCP.Add "english_cpCommon_301", " on "
dictLanguageCP.Add "english_cpCommon_302", " for "
dictLanguageCP.Add "english_cpCommon_303", "click here"
dictLanguageCP.Add "english_cpCommon_304", " days "
dictLanguageCP.Add "english_cpCommon_305", "Kgs."
dictLanguageCP.Add "english_cpCommon_306", "Grs."
dictLanguageCP.Add "english_cpCommon_307", "Lbs."
dictLanguageCP.Add "english_cpCommon_308", "Ozs."
dictLanguageCP.Add "english_cpCommon_310", "Yes"
dictLanguageCP.Add "english_cpCommon_311", "No"
dictLanguageCP.Add "english_cpCommon_312", "File Name"
dictLanguageCP.Add "english_cpCommon_313", "On"
dictLanguageCP.Add "english_cpCommon_314", "Off"
dictLanguageCP.Add "english_cpCommon_315", "Default"

dictLanguageCP.Add "english_cpCommon_400", "More information on this feature"
dictLanguageCP.Add "english_cpCommon_401", "Use HTML Editor"
dictLanguageCP.Add "english_cpCommon_402", "To select more than one entry, keep the CTRL button down while you select each entry."
dictLanguageCP.Add "english_cpCommon_403", "One of more fields were not filled in correctly."


dictLanguageCP.Add "english_cpCommon_500", "Page Layout"
dictLanguageCP.Add "english_cpCommon_501", "Use Default"
dictLanguageCP.Add "english_cpCommon_502", "Two Columns - Image on Right"
dictLanguageCP.Add "english_cpCommon_503", "Two Columns - Image on Left"
dictLanguageCP.Add "english_cpCommon_504", "One Column - Image Centered"
dictLanguageCP.Add "english_cpCommon_505", "As a list (category names only)"
dictLanguageCP.Add "english_cpCommon_506", "With category names and thumbnail images"
dictLanguageCP.Add "english_cpCommon_507", "In a drop-down"
dictLanguageCP.Add "english_cpCommon_508", "Categories per row"
dictLanguageCP.Add "english_cpCommon_509", "Rows per page"
dictLanguageCP.Add "english_cpCommon_510", "Display items <u>horizontally</u>, with images"
dictLanguageCP.Add "english_cpCommon_511", "Display items <u>vertically</u>"
dictLanguageCP.Add "english_cpCommon_512", "Display items <u>vertically</u> (list view)"
dictLanguageCP.Add "english_cpCommon_513", "Display items <u>vertically</u> (list view) with the ability to add multiple products to the cart in one step."
dictLanguageCP.Add "english_cpCommon_514", "Products per row"
dictLanguageCP.Add "english_cpCommon_515", "Show the product part number (SKU)"
dictLanguageCP.Add "english_cpCommon_516", "Show the small product thumbnail"
dictLanguageCP.Add "english_cpCommon_517", "Horizontally"
dictLanguageCP.Add "english_cpCommon_518", "Vertically"
dictLanguageCP.Add "english_cpCommon_519", "In a list"
dictLanguageCP.Add "english_cpCommon_520", "In a list (multiple Add to Cart)"


'// Search related

dictLanguageCP.Add "english_cpSearch_1", "Find Products"
dictLanguageCP.Add "english_cpSearch_2", "Find Customers"
dictLanguageCP.Add "english_cpSearch_3", "Product Search Results"
dictLanguageCP.Add "english_cpSearch_4", "Customer Search Results"
dictLanguageCP.Add "english_cpSearch_5", "Adv. Search"
dictLanguageCP.Add "english_cpSearch_6", "Continue"
dictLanguageCP.Add "english_cpSearch_7", "New Search"
dictLanguageCP.Add "english_cpSearch_8", "Keyword(s)"
dictLanguageCP.Add "english_cpSearch_9", "Enter value"
dictLanguageCP.Add "english_cpSearch_10", "Use the following filters to look for products in your store."
dictLanguageCP.Add "english_cpSearch_11", "Find a <strong>product</strong> by..."
dictLanguageCP.Add "english_cpSearch_12", "Find an <strong>order</strong> by..."
dictLanguageCP.Add "english_cpSearch_13", "Find Orders"
dictLanguageCP.Add "english_cpSearch_14", "Shipping Type"
dictLanguageCP.Add "english_cpSearch_15", "State Code"
dictLanguageCP.Add "english_cpSearch_16", "Country Code"
dictLanguageCP.Add "english_cpSearch_17", "We could not locate any orders."


'// Page Specific: format is "cp" & "pageName" & "number"

'// Menu.asp (Welcome page)
dictLanguageCP.Add "english_cpMenu_1", "Store" 
dictLanguageCP.Add "english_cpMenu_2", "&gt;&gt; Check for updates"
dictLanguageCP.Add "english_cpMenu_3", "Products &amp; Orders Quick Search"
dictLanguageCP.Add "english_cpMenu_4", "Recent Orders"
dictLanguageCP.Add "english_cpMenu_5", ""
dictLanguageCP.Add "english_cpMenu_6", ""
dictLanguageCP.Add "english_cpMenu_7", ""
dictLanguageCP.Add "english_cpMenu_8", ""
dictLanguageCP.Add "english_cpMenu_9", ""
dictLanguageCP.Add "english_cpMenu_10", ""
dictLanguageCP.Add "english_cpMenu_22", "Useful Links"
dictLanguageCP.Add "english_cpMenu_23", "Getting Started"
dictLanguageCP.Add "english_cpMenu_24", "Get started by configuring the following settings:"
dictLanguageCP.Add "english_cpMenu_25", "General Settings"
dictLanguageCP.Add "english_cpMenu_26", "Display Settings"
dictLanguageCP.Add "english_cpMenu_27", "E-mail Settings"
dictLanguageCP.Add "english_cpMenu_28", "Shipping Settings"
dictLanguageCP.Add "english_cpMenu_29", "Payment Settings"
dictLanguageCP.Add "english_cpMenu_30", "Tax Settings"
dictLanguageCP.Add "english_cpMenu_31", "Frequently Used Features"
dictLanguageCP.Add "english_cpMenu_32", "View Latest Orders"
dictLanguageCP.Add "english_cpMenu_33", "Find an Order"
dictLanguageCP.Add "english_cpMenu_34", "Find a Product"
dictLanguageCP.Add "english_cpMenu_35", "Add a New Product"
dictLanguageCP.Add "english_cpMenu_36", "Manage Categories"
dictLanguageCP.Add "english_cpMenu_37", "Edit Store Settings"
dictLanguageCP.Add "english_cpMenu_38", "View Sales Reports"
dictLanguageCP.Add "english_cpMenu_39", "Google Shopping Export"
dictLanguageCP.Add "english_cpMenu_40", "Storefront..."
dictLanguageCP.Add "english_cpMenu_41", "View Home Page"
dictLanguageCP.Add "english_cpMenu_42", "Browse by Category"
dictLanguageCP.Add "english_cpMenu_43", "Search Catalog"
dictLanguageCP.Add "english_cpMenu_44", "View Specials"
dictLanguageCP.Add "english_cpMenu_45", "View New Arrivals"
dictLanguageCP.Add "english_cpMenu_46", "View Best Sellers"
dictLanguageCP.Add "english_cpMenu_47", "Other Links..."
dictLanguageCP.Add "english_cpMenu_48", "Security Tips"
dictLanguageCP.Add "english_cpMenu_49", "Technical Support"
dictLanguageCP.Add "english_cpMenu_50", "Update Master User"
dictLanguageCP.Add "english_cpMenu_98", "Error calculating monthly sales on the page 'menu.asp'"
dictLanguageCP.Add "english_cpMenu_99", "A sales report for the current year cannot be created as no orders have yet been processed. Please note that pending, returned, and cancelled orders that might have been placed in the current year are not included in sales reports."
dictLanguageCP.Add "english_cpMenu_100", "<p>&nbsp;</p><p>Welcome to your store's Control Panel.</p><p style='margin-top: 10px;'>Note that <u>your Control Panel account has limited rights</u>. If you believe that you have not been given the correct access rights, please contact the store administrator.</p><p style='margin-top: 10px;'>To start using the Control Panel, use the navigation menus located at the top of the page. Mouse over each menu item to view a sub-menu of features to which you have been granted access.</p>"

'// Add/Modify Products (instPrd, modPrd)
dictLanguageCP.Add "english_cpSettings_1", "General Settings"
dictLanguageCP.Add "english_cpSettings_2", "Company Details"
dictLanguageCP.Add "english_cpSettings_3", "Order &amp; Customer Related"
dictLanguageCP.Add "english_cpSettings_4", "Display"
dictLanguageCP.Add "english_cpSettings_5", "Miscellaneous"
dictLanguageCP.Add "english_cpSettings_6", "Turn Store On &amp; Off"
dictLanguageCP.Add "english_cpSettings_7", "Turn Store ON"
dictLanguageCP.Add "english_cpSettings_8", "Turn Store OFF"
dictLanguageCP.Add "english_cpSettings_9", "Message displayed when store is OFF"
dictLanguageCP.Add "english_cpSettings_10", "Store Currency &amp; Date Formatting"
dictLanguageCP.Add "english_cpSettings_11", "Currency Sign"
dictLanguageCP.Add "english_cpSettings_12", "Decimal Format"
dictLanguageCP.Add "english_cpSettings_13", "Date Format"
dictLanguageCP.Add "english_cpSettings_14", "Secure Socket Layer URL (SSL)"
dictLanguageCP.Add "english_cpSettings_15", "Specify here whether or not your store will use SSL. For more information on SSL, <a href=http://wiki.earlyimpact.com/productcart/settings-general#secure_socket_layer_url_ssl target=_blank>see the documentation</a>."
dictLanguageCP.Add "english_cpSettings_16", "This store uses SSL"
dictLanguageCP.Add "english_cpSettings_17", "SSL URL"
dictLanguageCP.Add "english_cpSettings_18", "(e.g. https://www.mycompany.com or https://hostingprovider.mycompany.com)"
dictLanguageCP.Add "english_cpSettings_19", "Switch to secure page at"
dictLanguageCP.Add "english_cpSettings_20", "Registration/Login (Recommended) - A <u>dedicated SSL certificate</u> is required."
dictLanguageCP.Add "english_cpSettings_21", "Get one"
dictLanguageCP.Add "english_cpSettings_22", "Payment Gateway Page - You must select this option if yours is a shared SSL certificate. <a href=http://wiki.earlyimpact.com/productcart/settings-general#shared_ssl_certificates target=_blank>More information</a>."
dictLanguageCP.Add "english_cpSettings_23", "Store Home Page"
dictLanguageCP.Add "english_cpSettings_24", "Enter a URL only if you do <u>not</u> want to use ProductCart's default home page (<a href='../pc/home.asp' target='_blank'>view</a> - <a href='manageHomePage.asp'>manage</a>). Enter the full URL of the page that you would like to use as your store home page (e.g. http://www.mystore.com/myhome.html)."
dictLanguageCP.Add "english_cpSettings_25", "Home page URL"
dictLanguageCP.Add "english_cpSettings_26", "WishList &amp; Tell-a-Friend Settings"
dictLanguageCP.Add "english_cpSettings_27", "Enable <u>wish list</u> feature"
dictLanguageCP.Add "english_cpSettings_28", "Enable <u>tell-a-friend</u> feature"
dictLanguageCP.Add "english_cpSettings_29", "Company Logo"
dictLanguageCP.Add "english_cpSettings_30", "ProductCart uses this graphic in several printer-friendly pages (e.g. store invoices). By default, these pages show a &#147;Your Logo Here&#148; image. Here you can specify another image. In the &quot;Company logo&quot; field, enter the file name (no file path). ProductCart assumes that the file is in the &quot;productcart/pc/catalog&quot; directory on your Web server."
dictLanguageCP.Add "english_cpSettings_31", "Order &amp; Customer Related Settings"
dictLanguageCP.Add "english_cpSettings_32", "Set your customers' ability to place orders"
dictLanguageCP.Add "english_cpSettings_33", "All customers"
dictLanguageCP.Add "english_cpSettings_34", "Only wholesale customers"
dictLanguageCP.Add "english_cpSettings_35", "None of the customers"
dictLanguageCP.Add "english_cpSettings_36", "Max # of Products"
dictLanguageCP.Add "english_cpSettings_37", "Max # of Units"
dictLanguageCP.Add "english_cpSettings_38", "Minimum Order Amount"
dictLanguageCP.Add "english_cpSettings_39", "This is the minimum order amount for retail customers."
dictLanguageCP.Add "english_cpSettings_40", "Wholesale Minimum Order Amount"
dictLanguageCP.Add "english_cpSettings_41", "This is the minimum order amount for wholesale customers."
dictLanguageCP.Add "english_cpSettings_42", "Order Number Increase"
dictLanguageCP.Add "english_cpSettings_43", "Order numbers start with 1. If you would like to start at a higher number, insert the increase here. For example, if you enter 100, the first order will be 101."
dictLanguageCP.Add "english_cpSettings_44", "Customer Number Increase"
dictLanguageCP.Add "english_cpSettings_45", "Customer numbers start with 1. If you would like to start at a higher number, insert the increase here. For example, if you enter 100, the first customer number will be 101."
dictLanguageCP.Add "english_cpSettings_46", "Allow customers to checkout without registering a password"
dictLanguageCP.Add "english_cpSettings_47", "Allow users to 'nickname' their orders"
dictLanguageCP.Add "english_cpSettings_48", "Allow separate shipments"
dictLanguageCP.Add "english_cpSettings_49", "Allow customers to purchase out of stock items (disables ALL inventory features)"
dictLanguageCP.Add "english_cpSettings_50", "Category Display Options"
dictLanguageCP.Add "english_cpSettings_51", "Choose how <strong>categories and subcategories</strong> should be displayed"
dictLanguageCP.Add "english_cpSettings_52", "The following settings apply when categories are not displayed in a drop-down"
dictLanguageCP.Add "english_cpSettings_53", "Choose how <strong>products</strong> should be displayed in the storefront"
dictLanguageCP.Add "english_cpSettings_54", "The following settings define how many products are shown on a page."
dictLanguageCP.Add "english_cpSettings_55", "The following two settings only apply when products are shown in a list."
dictLanguageCP.Add "english_cpSettings_56", "Product sorting method within a category"
dictLanguageCP.Add "english_cpSettings_57", "Default product sorting preference"
dictLanguageCP.Add "english_cpSettings_58", "Product Part Number (SKU)"
dictLanguageCP.Add "english_cpSettings_59", "Product Name"
dictLanguageCP.Add "english_cpSettings_60", "High Price"
dictLanguageCP.Add "english_cpSettings_61", "Low Price"
dictLanguageCP.Add "english_cpSettings_62", "Product Details Page Display Options"
dictLanguageCP.Add "english_cpSettings_63", "Here you can define how information will be presented on the product details page."
dictLanguageCP.Add "english_cpSettings_64", "Don't let users sort products (&quot;Sort by&quot; drop-down menu is hidden)"
dictLanguageCP.Add "english_cpSettings_65", "User-selected product sorting"
dictLanguageCP.Add "english_cpSettings_66", "Miscellaneous Settings"
dictLanguageCP.Add "english_cpSettings_67", "Hide Category drop-down on Advanced Search page"
dictLanguageCP.Add "english_cpSettings_68", "Show &quot;Units in Stock&quot; on the product details page"
dictLanguageCP.Add "english_cpSettings_69", "Show &quot;Out of Stock&quot; message"
dictLanguageCP.Add "english_cpSettings_70", "Hide &quot;Enter Discount/Gift Certificate Code&quot; input field"
dictLanguageCP.Add "english_cpSettings_71", "Disallow Return Authorization request (RMA)"
dictLanguageCP.Add "english_cpSettings_72", "Turn built-in Help Desk ON/OFF"
dictLanguageCP.Add "english_cpSettings_73", "Turn search and product/category preview features ON/OFF (AJAX)"
dictLanguageCP.Add "english_cpSettings_74", "Turn error handler ON/OFF (debugging tool)"
dictLanguageCP.Add "english_cpSettings_75", "Disable Gift Registries"
dictLanguageCP.Add "english_cpSettings_76", "Allow the use of discount codes when any product in the shopping cart is 'On Sale'"

'// Add/Modify Categories (instCat, modCat)
dictLanguageCP.Add "english_cpInstCat_0", "Add New Category"
dictLanguageCP.Add "english_cpInstCat_1", "Category Name, Images and Parent Category"
dictLanguageCP.Add "english_cpInstCat_2", "Small Image" 
dictLanguageCP.Add "english_cpInstCat_3", "Large Image" 
dictLanguageCP.Add "english_cpInstCat_5", "Category Descriptions" 
dictLanguageCP.Add "english_cpInstCat_6", "Do not show category descriptions" 
dictLanguageCP.Add "english_cpInstCat_7", "Short Description" 
dictLanguageCP.Add "english_cpInstCat_8", "Shown on pages that display categories" 
dictLanguageCP.Add "english_cpInstCat_9", "Long Description" 
dictLanguageCP.Add "english_cpInstCat_10", "Only shown on the page that displays products within the category" 
dictLanguageCP.Add "english_cpInstCat_11", "Display Settings" 
dictLanguageCP.Add "english_cpInstCat_12", "Choose a display option for how " 
dictLanguageCP.Add "english_cpInstCat_13", "subcategories" 
dictLanguageCP.Add "english_cpInstCat_14", " are displayed (if no option is selected, the default <a href='AdminSettings.asp?tab=3'>store-wide setting</a> is used)" 
dictLanguageCP.Add "english_cpInstCat_15", "Display products" 
dictLanguageCP.Add "english_cpInstCat_16", "The following settings regulate how many products are shown (if empty or 0, the default <a href='AdminSettings.asp?tab=3'>store-wide setting</a> is used)" 
dictLanguageCP.Add "english_cpInstCat_17", "Choose a display option for how " 
dictLanguageCP.Add "english_cpInstCat_18", "products" 
dictLanguageCP.Add "english_cpInstCat_19", " are displayed (if no option is selected, the default <a href='AdminSettings.asp?tab=3'>store-wide setting</a> is used)" 
dictLanguageCP.Add "english_cpInstCat_20", "Restrict the visibility of this category (the products that it contains are also hidden)"
dictLanguageCP.Add "english_cpInstCat_21", "Hide this category in the storefront" 
dictLanguageCP.Add "english_cpInstCat_22", "Hide this category in the storefront from retail customers (wholesale customers can see it)" 
dictLanguageCP.Add "english_cpInstCat_23", "Product Details Page Display Options" 
dictLanguageCP.Add "english_cpInstCat_24", "Choose a display option for the product details page. It will apply to all products within this category. This option <a href='AdminSettings.asp?tab=3'>overrides the storewide setting</a>. You can also define this setting at the product level when adding/editing products." 
dictLanguageCP.Add "english_cpInstCat_25", "Category Meta Tags" 
dictLanguageCP.Add "english_cpInstCat_26", "Enter Meta Tags specific to this category." 
dictLanguageCP.Add "english_cpInstCat_27", "Title"
dictLanguageCP.Add "english_cpInstCat_28", "Description"
dictLanguageCP.Add "english_cpInstCat_29", "Keywords"


'// Add/Modify Products (instPrd, modPrd)
dictLanguageCP.Add "english_cpInstPrd_1", "Add a New Product"
dictLanguageCP.Add "english_cpInstPrd_2", "Clone an existing product &gt;&gt;" 
dictLanguageCP.Add "english_cpInstPrd_3", "Click on this link to locate the product, then click on &quot;Clone&quot;." 
dictLanguageCP.Add "english_cpInstPrd_4", "Name, SKU and Descriptions" 
dictLanguageCP.Add "english_cpInstPrd_5", "Product Prices" 
dictLanguageCP.Add "english_cpInstPrd_6", "This price will override the default price for this pricing category" 
dictLanguageCP.Add "english_cpInstPrd_7", "Product Images"
dictLanguageCP.Add "english_cpInstPrd_8", "To upload and resize an image "
dictLanguageCP.Add "english_cpInstPrd_9", "To upload an image "
dictLanguageCP.Add "english_cpInstPrd_10", "Thumbnail Image"
dictLanguageCP.Add "english_cpInstPrd_11", "General Image"
dictLanguageCP.Add "english_cpInstPrd_12", "Detail View Image"
dictLanguageCP.Add "english_cpInstPrd_13", "Inventory Settings"
dictLanguageCP.Add "english_cpInstPrd_14", "Disregard Stock"
dictLanguageCP.Add "english_cpInstPrd_15", "Current Stock Level"
dictLanguageCP.Add "english_cpInstPrd_16", "Minimum Quantity to Buy"
dictLanguageCP.Add "english_cpInstPrd_17", "Force purchase of multiples of:"
dictLanguageCP.Add "english_cpInstPrd_18", "Allow back-ordering"
dictLanguageCP.Add "english_cpInstPrd_19", "Typically ships within "
dictLanguageCP.Add "english_cpInstPrd_20", "Low inventory notification"
dictLanguageCP.Add "english_cpInstPrd_21", "Reorder Level"
dictLanguageCP.Add "english_cpInstPrd_22", "Other Settings"
dictLanguageCP.Add "english_cpInstPrd_23", "Product is drop-shipped"
dictLanguageCP.Add "english_cpInstPrd_24", "Not for Sale"
dictLanguageCP.Add "english_cpInstPrd_25", "Message to display (e.g. 'Coming Soon')"
dictLanguageCP.Add "english_cpInstPrd_26", "Non-Taxable"
dictLanguageCP.Add "english_cpInstPrd_27", "Units to make 1 Kg"
dictLanguageCP.Add "english_cpInstPrd_28", "If this product weighs less than one gram, use the field below to specify how many units of this product it takes to weigh 1 KG. For more information, see the User Guide"
dictLanguageCP.Add "english_cpInstPrd_29", "Units to make 1 Lb"
dictLanguageCP.Add "english_cpInstPrd_30", "If this product weighs less than one ounce, use the field below to specify how many units of this product it takes to weigh 1 pound. For more information, see the User Guide."
dictLanguageCP.Add "english_cpInstPrd_31", "No Shipping"
dictLanguageCP.Add "english_cpInstPrd_32", "Display No Shipping Text"
dictLanguageCP.Add "english_cpInstPrd_33", "<strong>Oversized</strong> products shipped via <strong>UPS, FedEx or USPS</strong><br>Indicate whether this is an oversized product. If yes, specify the package size below)."
'// _34 does not need to be translated in countries where UPS is not used
dictLanguageCP.Add "english_cpInstPrd_34", "Notes about shipping oversized packages via UPS:<br>&gt; &quot;Length&quot; should always be the longest side<br>&gt; Any one side, cannot exceed 108&quot; in length<br>&gt; (length + girth) cannot exceed 130lbs<br>&gt; &quot;Girth&quot; is defined as: (width*2) + (height*2)<br>&gt; For more information, "
dictLanguageCP.Add "english_cpInstPrd_35", "UPS, THE UPS SHIELD TRADEMARK, THE UPS READY MARK, <br />THE UPS ONLINE TOOLS MARK AND THE COLOR BROWN ARE TRADEMARKS OF <br />UNITED PARCEL SERVICE OF AMERICA, INC. ALL RIGHTS RESERVED."
dictLanguageCP.Add "english_cpInstPrd_36", "Downloadable Product Settings"
dictLanguageCP.Add "english_cpInstPrd_37", "This is a downloadable product"
dictLanguageCP.Add "english_cpInstPrd_38", "Downloadable file location. You have <u>two options</u>:"
dictLanguageCP.Add "english_cpInstPrd_39", "<u>Enter the full physical path to the file</u> (e.g. M:\myAccount\downloads\downloadfile.zip). This option uses the <em>Hide URL </em>feature. On Web servers running IIS 6 or above, this feature only works with files that are less than 4 MB in size. For more information and a technical explanation of this feature, please see the User Guide."
dictLanguageCP.Add "english_cpInstPrd_40", "Current physical path of the root directory: "
dictLanguageCP.Add "english_cpInstPrd_41", "<u>Enter the full HTTP path to the file</u> (e.g.  http://www.myStore.com/downloads/downloadfile.zip). This option does not use the <em>Hide URL </em>feature. There is no limitation on the file size, regardless of the version of IIS used on the Web server. For more information, please see the User Guide."
dictLanguageCP.Add "english_cpInstPrd_42", "Make download URL expire:"
dictLanguageCP.Add "english_cpInstPrd_43", "URL will expire after: "
dictLanguageCP.Add "english_cpInstPrd_44", "Generate and deliver a license, serial number, etc. with the order confirmation: "
dictLanguageCP.Add "english_cpInstPrd_45", "<b>1.</b> Use local license generator. Enter  file name:<br><font color=#333>Note: Upload license generator script to the folder &quot;/productcart/pcadmin/licenses&quot; and enter the filename in the text box below (e.g. myLicense.asp). <a href='http://www.earlyimpact.com/pdf/productcart_dpm.pdf' target='_blank'>More information</a></font>"
dictLanguageCP.Add "english_cpInstPrd_46", "<b>2.</b> Use remote license generator. Enter URL to file:<br><font color=#333>Note: enter the full URL, starting with HTTP:// (e.g. http://www.myWeb.com/myLicense.asp). <a href='http://www.earlyimpact.com/pdf/productcart_dpm.pdf' target='_blank'>More information</a></font>"
dictLanguageCP.Add "english_cpInstPrd_47", "Your license generator can return to ProductCart up 5 variables. Enter the descriptive names for those variables. <a href='http://www.earlyimpact.com/pdf/productcart_dpm.pdf' target='_blank'>More information</a>"
dictLanguageCP.Add "english_cpInstPrd_48", "License Field"
dictLanguageCP.Add "english_cpInstPrd_49", "Additional copy for confirmation e-mail (e.g. installation instructions)"
dictLanguageCP.Add "english_cpInstPrd_50", "Gift Certificate Settings"
dictLanguageCP.Add "english_cpInstPrd_51", "This is a Gift Certificate"
dictLanguageCP.Add "english_cpInstPrd_52", "Expiration"
dictLanguageCP.Add "english_cpInstPrd_53", "Does not expire"
dictLanguageCP.Add "english_cpInstPrd_54", "Expires on a specific date: "
dictLanguageCP.Add "english_cpInstPrd_55", "Expires in the following number of days after the purchase: "
dictLanguageCP.Add "english_cpInstPrd_56", "Electronic Only"
dictLanguageCP.Add "english_cpInstPrd_57", "How is the unique Gift Certificate code generated?"
dictLanguageCP.Add "english_cpInstPrd_58", "Using the built-in code generator"
dictLanguageCP.Add "english_cpInstPrd_59", "Using the following script (enter file name): "
dictLanguageCP.Add "english_cpInstPrd_60", "Note: Upload your custom gift certificate code generator script to the folder &quot;pcadmin/licenses&quot; and enter the file name in the input field above (e.g. myGiftCode.asp)"
dictLanguageCP.Add "english_cpInstPrd_61", "In which top-level category will this product be located?"
dictLanguageCP.Add "english_cpInstPrd_62", "Add this product to a <u><strong>new</strong> category</u>"
dictLanguageCP.Add "english_cpInstPrd_63", "...or add it to <u><strong>existing</strong> categories</u>."

dictLanguageCP.Add "english_cpInstPrd_87", "Product Notes:"
dictLanguageCP.Add "english_cpInstPrd_88", "Note:"
dictLanguageCP.Add "english_cpInstPrd_89", "All adjustments will take effect only when you add this product to database."
dictLanguageCP.Add "english_cpInstPrd_90", "All adjustments will take effect only when you save this product."
dictLanguageCP.Add "english_cpInstPrd_91", "Add new search field values to this product"
dictLanguageCP.Add "english_cpInstPrd_92", "Custom Field:"
dictLanguageCP.Add "english_cpInstPrd_93", "Value:"
dictLanguageCP.Add "english_cpInstPrd_94", "New Value:"
dictLanguageCP.Add "english_cpInstPrd_95", "Order:"
dictLanguageCP.Add "english_cpInstPrd_96", "Hide SKU on the product details page"

	'// Apparel-specific
dictLanguageCP.Add "english_cpInstPrd_70", "Apparel Product Settings"
dictLanguageCP.Add "english_cpInstPrd_71", "This is an apparel product"
dictLanguageCP.Add "english_cpInstPrd_72", "When a Sub-Product is out of stock (e.g. &quot;Blue/Large&quot; is out of stock)..."
dictLanguageCP.Add "english_cpInstPrd_73", "Hide the selectable option <font color='#666'>(e.g. if &quot;Blue&quot; is selected, &quot;Large&quot; is not shown)</font>"
dictLanguageCP.Add "english_cpInstPrd_74", "Show a custom message next to the option:"
dictLanguageCP.Add "english_cpInstPrd_75", "<font color='#666'>(e.g. if &quot;Blue&quot; is selected, &quot;Large - <em>Custom Message </em>&quot; is  shown)</font>"
dictLanguageCP.Add "english_cpInstPrd_76", "Display choices (e.g. 'Colors', 'Sizes', etc.):"
dictLanguageCP.Add "english_cpInstPrd_77", "Using drop down menus"
dictLanguageCP.Add "english_cpInstPrd_78", "Using radio buttons"
dictLanguageCP.Add "english_cpInstPrd_79", "More details pop-up window (e.g. 'Size Chart'):"
dictLanguageCP.Add "english_cpInstPrd_80", "Text link to launch the pop-up <br> (e.g. 'View Size Chart')"
dictLanguageCP.Add "english_cpInstPrd_81", "Text to show in the pop-up <br> (supports HTML tags):"
dictLanguageCP.Add "english_cpInstPrd_82", "Image <br> (you can load an image file instead):"
dictLanguageCP.Add "english_cpInstPrd_83", "<font color='#666'>Type in the file name, no file path. All images must be located in the 'pc/catalog' folder. If you use the Text field, the image is shown to the right of the text.</font>"
dictLanguageCP.Add "english_cpInstPrd_84", "<font color='#666'>Upload a new image</font>"
dictLanguageCP.Add "english_cpInstPrd_85", "URL:"
dictLanguageCP.Add "english_cpInstPrd_86", "<font color='#666'>The URL is loaded in the pop-up window (e.g. Web page, image, PDF, etc.).</font>"

'// Alert Messages
dictLanguageCP.Add "english_cpAlert_0", "This icon indicates required fields."
dictLanguageCP.Add "english_cpAlert_1", "Please enter a SKU or part number."
dictLanguageCP.Add "english_cpAlert_2", "Please enter a name for the product."
dictLanguageCP.Add "english_cpAlert_3", "Please enter a description for the product."
dictLanguageCP.Add "english_cpAlert_4", "Please select at least one category from the list."
dictLanguageCP.Add "english_cpAlert_5", "Please enter the full physical path to the downloadable file"
dictLanguageCP.Add "english_cpAlert_6", "Please enter a number for this field."
dictLanguageCP.Add "english_cpAlert_7", "Please enter a number greater than zero for this field."
dictLanguageCP.Add "english_cpAlert_8", "Please fill out one of the License Generator fields."
dictLanguageCP.Add "english_cpAlert_9", "Please fill out only one of License Generator fields."
dictLanguageCP.Add "english_cpAlert_10", "Please fill out at least one of the License Label fields."
dictLanguageCP.Add "english_cpAlert_11", "Please enter a valid date for this field."
dictLanguageCP.Add "english_cpAlert_12", "Please fill out the File Name field."

'// FedEx Shipping Manager
dictLanguageCP.Add "english_cpFedEx_0", "This icon indicates required fields."
dictLanguageCP.Add "english_cpFedEx_1", "Carrier Code is a required field."
dictLanguageCP.Add "english_cpFedEx_2", "Ship Date is a required field."
dictLanguageCP.Add "english_cpFedEx_3", "Ship Time is a required field."
dictLanguageCP.Add "english_cpFedEx_4", "Origin Person Name is a required field."
dictLanguageCP.Add "english_cpFedEx_5", "Origin Company Name is a required field."
dictLanguageCP.Add "english_cpFedEx_6", "Origin Phone Number is a required field."
dictLanguageCP.Add "english_cpFedEx_7", "Origin Email Address is a required field."
dictLanguageCP.Add "english_cpFedEx_8", "Origin Line 1 is a required field."
dictLanguageCP.Add "english_cpFedEx_9", "Origin City is a required field."
dictLanguageCP.Add "english_cpFedEx_10", "Origin Postal Code is a required field."
dictLanguageCP.Add "english_cpFedEx_11", "Origin Country Code is a required field."
dictLanguageCP.Add "english_cpFedEx_12", "Recipient Person Name is a required field."
dictLanguageCP.Add "english_cpFedEx_13", "Recipient Phone Number is a required field."
dictLanguageCP.Add "english_cpFedEx_14", "Recipient Country Code is a required field."
dictLanguageCP.Add "english_cpFedEx_15", "Recipient Line 1 is a required field."
dictLanguageCP.Add "english_cpFedEx_16", "Recipient City is a required field."
dictLanguageCP.Add "english_cpFedEx_17", "Customer Reference is a required field."

'// Control Panel Password Reminder
dictLanguageCP.Add "english_forgotusernameadminmailfromName", scCompanyName
dictLanguageCP.Add "english_forgotusernameadminmailsubject", "Your User Name"
dictLanguageCP.Add "english_forgotusernameadminmailbody1", "Hello Store Administrator." &VBcrlf &VBcrlf & "Your requested User Name is: #username" &VBcrlf &VBcrlf 
dictLanguageCP.Add "english_forgotusernameadminsuccess", "We have sent you User Name to the e-mail address you supplied. You should receive it shortly."
dictLanguageCP.Add "english_forgotusernameadminerror", "You did not enter the correct administrator e-mail address."
dictLanguageCP.Add "english_forgotusernameadminDBerror", "There was an error. The error is: "

dictLanguageCP.Add "english_forgotpasswordadminmailfromName", scCompanyName
dictLanguageCP.Add "english_forgotpasswordadminmailsubject", "Your Password"
dictLanguageCP.Add "english_forgotpasswordadminmailbody1", "Hello Store Administrator." &VBcrlf &VBcrlf & "Your requested Password is: #password" &VBcrlf &VBcrlf 
dictLanguageCP.Add "english_forgotpasswordadminsuccess", "We have sent your new Password to the store administrator's e-mail address. You should receive it shortly."
dictLanguageCP.Add "english_forgotpasswordadminerror", "The User Name you entered is not a valid administrator User Name."
dictLanguageCP.Add "english_forgotpasswordadminDBerror", "There was an error. The Error number is: "
dictLanguageCP.Add "english_forgotpassword_securityMessage", "This feature has been locked to prevent unauthorized access. You will need to close all browser windows and restart your browser to try using this feature again."
%>