<%private const pTaxonCharges=0
private const pTaxonFees=0
private const ptaxfile=1
private const ptaxsetup=1
private const ptaxshippingaddress="1"
private const ptaxseparate="0"
private const ptaxwholesale="0"
private const pshowVatID="0"
private const pVatIdReq="0"
private const pshowSSN="0"
private const pSSNReq="0"
private const ptaxVATrate="0"
private const ptaxVATRate_Code=""
private const ptaxVAT="0"
private const ptaxdisplayVAT="0"
private const ptaxRateDefault="8.375, "
private const ptaxRateState="OK, "
private const ptaxSNH="NN, "
private const ptaxCanada="0"
private const ptaxfilename="csv1213.csv"%>